services:
  seanime:
    image: umagistr/seanime:v3.10.3-rootless
    container_name: seanime
    restart: unless-stopped

    user: "1000:1000"

    ports:
      - "127.0.0.1:43211:43211"

    # Server password is set in ./data/config.toml under [server] (password = "your_password")
    environment:
      - TZ=Asia/Kolkata
      - SEANIME_SERVER_HOST=0.0.0.0

    volumes:
      - ./data:/home/seanime/.config/Seanime
      - /srv/media2/seanime:/media2
